POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"ahmed amrawy",
    "number": 123123123123
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 123123123123
}